### PR TITLE
Featuer/lerna

### PR DESCRIPTION
**Pull request by chandlerprall**
Moved `insula` code into packages/insula, moved `react-insula` code from separate repo into packages/react-insula. insula-immutable and insula-stringselectors will come in after v3 middleware is figured out.

### CODE REVIEW

**Review by hartzis — APPROVED** [review]
This is an awesome change! I'd probably suggest publish patches for `react-insula` and `insula` after you merge this in?

**Review by michaelmerrill — APPROVED** [review]
This is the first I've heard of Lerna. Looks really cool. Is there a reason to do the eslint configs in every package.json or can we share one across all packages. Nice work!

**Comment by chandlerprall** [comment]
@hartzis this included a major version bump for both packages

**Comment by chandlerprall** [comment]
@michaelmerrill good catch, I'll consolidate them

**Pull request merged**
